#!/bin/bash
set -eu

check_char='\xE2\x9C\x93'
cross_char='\xE2\x9C\x96'
green='\033[0;32m'
red='\033[0;31m'
nc='\033[0m'
check="$green$check_char$nc"
cross="$red$cross_char$nc"

printf "test"

if result=$(cargo test 2>&1); then
    echo " $check"
else
    echo " $cross"
    echo " $result"
    exit 1
fi
